#!/usr/bin/env bash
# test/ring/make_delivery_manifest.sh — produce the delivery manifest (feature 101,
# supporting T022 · FR-005).
#
# The manifest enumerates what the capability actually DELIVERS: the L0 contract plus the
# per-ring realizations, all of it under glp_gleam/. It exists so that FR-005 — a NEGATIVE
# requirement — has something concrete to be checked against.
#
# glpnet's delivery mode is RESYNTHESIS, NEVER COPY. `glp_runtime/` (the Dart reference),
# `glp_multiagent/` (the Flutter app) and `programs/` (the .glp corpus) are RETAINED here
# and delivered nowhere: they are the oracle the rings are measured against, not cargo.
# Nothing fails if a copy quietly appears in the delivered set — everything still builds,
# everything still passes — which is exactly why the guard has to be explicit rather than
# trusted. test/ring/test_retention.sh reads this file.
#
# Usage: bash test/ring/make_delivery_manifest.sh
# Exit:  0 written · 2 setup.

set -u
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
SURFACE="$SCRIPT_DIR/contract-surface.list"
MANIFEST="$SCRIPT_DIR/delivery-manifest.txt"

[ -f "$SURFACE" ] || { echo "make_delivery_manifest: missing $SURFACE (run T012/T013 first)" >&2; exit 2; }

{
    echo "# test/ring/delivery-manifest.txt — the delivered set (feature 101, FR-005)."
    echo "#"
    echo "# Generated by test/ring/make_delivery_manifest.sh. Repo-relative paths."
    echo "#"
    echo "# Delivered: the L0 contract + the per-ring realizations, all under glp_gleam/."
    echo "# NOT delivered, deliberately: glp_runtime/ (Dart reference), glp_multiagent/"
    echo "# (Flutter app), programs/ (the .glp corpus). Those are RETAINED as the oracle."
    echo "# glpnet resynthesizes; it does not copy."
    echo "#"
    echo "# generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo ""

    echo "# --- L0 contract (runtime-free; enforced by check_contract_purity.sh) ---"
    find "$REPO_ROOT/glp_gleam/src/glp/contract" -name '*.gleam' 2>/dev/null \
        | sed "s|^$REPO_ROOT/||" | tr '\\' '/' | sort

    echo ""
    echo "# --- ring realizations (each may depend on exactly one runtime) ---"
    find "$REPO_ROOT/glp_gleam/src/glp/ring" -name '*.gleam' 2>/dev/null \
        | sed "s|^$REPO_ROOT/||" | tr '\\' '/' | sort

    echo ""
    echo "# --- the measured runtime-free surface the contract admits ---"
    while IFS= read -r mod; do
        mod="${mod%$'\r'}"
        case "$mod" in ''|'#'*) continue ;; esac
        f="glp_gleam/src/$mod.gleam"
        [ -f "$REPO_ROOT/$f" ] && echo "$f"
    done < "$SURFACE"

    echo ""
    echo "# --- build metadata ---"
    echo "glp_gleam/gleam.toml"
    [ -f "$REPO_ROOT/glp_gleam/manifest.toml" ] && echo "glp_gleam/manifest.toml"
} > "$MANIFEST"

COUNT="$(grep -c '^glp_gleam/' "$MANIFEST")"
echo "wrote $MANIFEST — $COUNT delivered file(s), all under glp_gleam/"
exit 0
