{application,snabbkaffe,
             [{description,"Simple trace-based testing framework"},
              {vsn,"1.0.10"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[asciiart,snabbkaffe,snabbkaffe_collector,
                        snabbkaffe_diff,snabbkaffe_nemesis,snabbkaffe_sup]},
              {licenses,["Apache 2.0"]},
              {links,[{"Github",
                       "https://github.com/kafka4beam/snabbkaffe"}]}]}.
